version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306"   #localhost:3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
       interval: 5s
       timeout: 5s
       retries: 10


  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8080:8080" #localhost:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=todo_db;user=root;password=12345
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "5173:80"   #localhost:5173
    depends_on:
      - backend
    networks:
      - todo-network



networks:
  todo-network:

volumes:
  mysql_data:
